export const nation = [
    { text: '土家族', value: 'TJ', num: '15' },
    { text: '土族', value: 'TU', num: '30' },
    { text: '门巴族', value: 'MB', num: '54' },
    { text: '水族', value: 'SU', num: '25' },
    { text: '毛南族', value: 'MN', num: '36' },
    { text: '乌兹别克族', value: 'UZ', num: '43' },
    { text: '布依族', value: 'BY', num: '09' },
    { text: '布朗族', value: 'BL', num: '34' },
    { text: '东乡族', value: 'DX', num: '26' },
    { text: '仡佬族', value: 'GL', num: '37' },
    { text: '仫佬族', value: 'ML', num: '32' },
    { text: '白族', value: 'BA', num: '14' },
    { text: '汉族', value: 'HA', num: '01' },
    { text: '达斡尔族', value: 'DU', num: '31' },
    { text: '回族', value: 'HU', num: '03' },
    { text: '佤族', value: 'VA', num: '21' },
    { text: '壮族', value: 'ZH', num: '08' },
    { text: '羌族', value: 'QI', num: '33' },
    { text: '阿昌族', value: 'AC', num: '29' },
    { text: '纳西族', value: 'NX', num: '27' },
    { text: '拉祜族', value: 'LH', num: '24' },
    { text: '苗族', value: 'MH', num: '06' },
    { text: '侗族', value: 'DO', num: '12' },
    { text: '京族', value: 'GI', num: '49' },
    { text: '柯尔克孜族', value: 'KG', num: '29' },
    { text: '哈尼族', value: 'HN', num: '16' },
    { text: '哈萨克族', value: 'KZ', num: '17' },
    { text: '保安族', value: 'BN', num: '47' },
    { text: '俄罗斯族', value: 'RS', num: '44' },
    { text: '独龙族', value: 'DR', num: '51' },
    { text: '怒族', value: 'NU', num: '42' },
    { text: '珞巴族', value: 'LB', num: '55' },
    { text: '高山族', value: 'GS', num: '23' },
    { text: '基诺族', value: 'JN', num: '56' },
    { text: '鄂伦春族', value: 'OR', num: '52' },
    { text: '鄂温克族', value: 'EW', num: '45' },
    { text: '维吾尔族', value: 'UG', num: '05' },
    { text: '塔吉克族', value: 'TA', num: '41' },
    { text: '塔塔尔族', value: 'TT', num: '50' },
    { text: '朝鲜族', value: 'CS', num: '10' },
    { text: '景颇族', value: 'JP', num: '28' },
    { text: '傣族', value: 'DA', num: '18' },
    { text: '傈僳族', value: 'LS', num: '20' },
    { text: '畲族', value: 'SH', num: '22' },
    { text: '普米族', value: 'PM', num: '40' },
    { text: '裕固族', value: 'YG', num: '48' },
    { text: '蒙古族', value: 'MG', num: '02' },
    { text: '锡伯族', value: 'XB', num: '38' },
    { text: '满族', value: 'MA', num: '11' },
    { text: '瑶族', value: 'YA', num: '13' },
    { text: '赫哲族', value: 'HZ', num: '53' },
    { text: '撒拉族', value: 'SL', num: '35' },
    { text: '德昂族', value: 'DE', num: '46' },
    { text: '黎族', value: 'LI', num: '19' },
    { text: '藏族', value: 'ZA', num: '04' },
    { text: '彝族', value: 'YI', num: '07' },
];

export const face = [
    { value: '01', text: '中共党员' },
    { value: '02', text: '中共预备党员' },
    { value: '03', text: '共青团员' },
    { value: '04', text: '民革会员' },
    { value: '05', text: '民盟盟员' },
    { value: '06', text: '民建会员' },
    { value: '07', text: '民进会员' },
    { value: '08', text: '农工党党员' },
    { value: '09', text: '致公党党员' },
    { value: '10', text: '九三学社社员' },
    { value: '11', text: '台盟盟员' },
    { value: '12', text: '无党派民主人士' },
    { value: '13', text: '群众' },
]

export const education = [
    { text: '小学', value: 'primary_school' },
    { text: '初中', value: 'junior_middle' },
    { text: '中专/高中', value: 'secondary_specialized' },
    { text: '专科', value: 'specialty' },
    { text: '本科', value: 'undergraduate' },
    { text: '硕士', value: 'master' },
    { text: '博士', value: 'doctor' },
]

export const UserStatus = [
    {
        value: false,
        text: '禁用',
    },
    {
        value: true,
        text: '启用',
    },
]

export const JobStatus = [
    {
        value: 'online',
        text: '在职',
    },
    {
        value: 'vacation',
        text: '休假',
    },
    {
        value: 'quit',
        text: '离职',
    },
]
